development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: posten_agent_api_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: posten_agent_api_test
  pool: 5

